name: Node CI Run all tests

on: 
  push:
    branches-ignore:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: yarn
    - name: Run tests
      run: yarn test
